"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import type { CaseListItem } from "../../types/api";
import { Card, StatusBadge, money } from "./ui";

type SortKey = "amount" | "recovered";

export function CasesTable({ cases, loading }: { cases: CaseListItem[]; loading: boolean }) {
  const [sort, setSort] = useState<SortKey>("amount");
  const ordered = useMemo(() => [...cases].sort((a, b) => sort === "amount" ? b.amount_paise - a.amount_paise : b.recovered_amount_paise - a.recovered_amount_paise), [cases, sort]);
  return <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-800 p-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold">Recovery cases</h2><p className="mt-1 text-sm text-slate-400">Real cases from the selected batch. Select one to inspect its audit trail.</p></div><div className="flex gap-2"><button className={`rounded-lg px-3 py-2 text-sm ${sort === "amount" ? "bg-cyan-400 font-semibold text-slate-950" : "bg-slate-800 text-slate-300"}`} onClick={() => setSort("amount")}>Sort amount</button><button className={`rounded-lg px-3 py-2 text-sm ${sort === "recovered" ? "bg-cyan-400 font-semibold text-slate-950" : "bg-slate-800 text-slate-300"}`} onClick={() => setSort("recovered")}>Sort recovered</button></div></div><div className="overflow-x-auto"><table className="min-w-[920px] w-full text-left text-sm"><thead className="bg-slate-950/50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-4">Payment case</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Diagnosis</th><th className="px-5 py-4">Action</th><th className="px-5 py-4">Policy / case</th><th className="px-5 py-4">Outcome</th><th className="px-5 py-4">Recovered</th></tr></thead><tbody>{loading ? Array.from({ length: 4 }).map((_, index) => <tr key={index} className="border-t border-slate-800"><td colSpan={8} className="px-5 py-5"><div className="h-5 w-full animate-pulse rounded bg-slate-800" /></td></tr>) : ordered.map((item) => <tr key={item.case_id} className="border-t border-slate-800 transition hover:bg-slate-800/50"><td className="px-5 py-4 font-mono text-xs text-cyan-300"><Link href={`/cases/${item.case_id}`} className="hover:underline">{item.case_id.slice(0, 12)}…</Link></td><td className="px-5 py-4"><Link href={`/cases/${item.case_id}`} className="font-medium text-white hover:text-cyan-300">{item.customer ?? "Unknown customer"}</Link></td><td className="px-5 py-4">{money(item.amount_paise)}</td><td className="px-5 py-4 text-slate-300">{item.diagnosis.replaceAll("_", " ")}</td><td className="px-5 py-4 text-slate-300">{item.action?.replaceAll("_", " ") ?? "—"}</td><td className="px-5 py-4"><StatusBadge value={item.status} positive={item.status === "allowed" || item.status === "success"} negative={item.status === "stopped" || item.status === "failed"} /></td><td className="px-5 py-4"><span className="text-slate-400">Case detail</span></td><td className="px-5 py-4 font-medium text-emerald-300">{money(item.recovered_amount_paise)}</td></tr>)}{!loading && !ordered.length && <tr><td colSpan={8} className="px-5 py-12 text-center text-slate-400">No recovery cases were created for this batch.</td></tr>}</tbody></table></div></Card>;
}
