ALTER TABLE recovery_batches
  ADD COLUMN IF NOT EXISTS cases_analyzed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS revenue_at_risk_paise INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS actions_executed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stopped_by_policy INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS successful_recoveries INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS failed_recoveries INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pending_recoveries INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_revenue_recovered_paise INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS metrics_by_diagnosis JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS metrics_by_action JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE recovery_cases
  ADD COLUMN IF NOT EXISTS execution_status TEXT,
  ADD COLUMN IF NOT EXISTS execution_result JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS outcome_status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS outcome_checked_at TIMESTAMPTZ;
